export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Project } from "./Project";
export { default as ComingSoonPage } from "./ComingSoonPage";
export { default as NotFound } from "./NotFound";
export { default as Blog } from "./Blog";
export { default as GuidedPaths } from "./GuidedPaths";
export { default as Contact } from "./Contact";
